	#include "std_lib_facilities.h"

	int main()
	{
		int a = 20000;
		char c = a;
		int b = c;

		if (a != b)
		{
			cout << "\nWhoopss. Something Went Wrong\n";
		}

		else
		{
			cout << "\nThats A Big Number!\n";
		}

		/* EXPLANATION: int = 4byte Value. char = 1byte. c = a Results in c Being Overloaded. 
		   b Then Whatever Garbage Value Is Generated By Trying To Force 20,000 into 8 bits */
		cout << "Results: "
			 << "\na = " << a
			 << "\nb = " << b
			 << "\nc = " << c;
		
		keep_window_open();

	}